### PR TITLE
180348539 update project

### PR DESCRIPTION
**Pull request by kswenson**
Update project dependencies, notably:
- Webpack 5
- React 17
- three.js 0.135

Migrate to TypeScript

Testable at: https://models-resources.concord.org/grasp-seasons/branch/180348539-update-project/index.html

### CODE REVIEW

**Review by pjanik — CHANGES_REQUESTED** [review]
I have the same error as on TravisCI. It seems you removed `webpack.config.js`. Webpack 5 works without any config, but I bet that it wasn't intentional. 😉

**Comment by kswenson** [comment]
> It seems you removed `webpack.config.js`. Webpack 5 works without any config, but I bet that it wasn't intentional. 😉

🤦 Clearly not intentional. I can't even figure out how it happened -- it still existed locally on my machine. 😕 Anyway, in adding it back I realized there were a couple of other .ts files that should have been added as well. They should all be there now.

And look -- when you check in all the files the CI build completes successfully! 😉

**Comment by pjanik** [comment]
It builds now locally too, thanks. :)

My main concern is that the layout got a bit broken. 

- That's the local version: Screenshot 2021-12-16 at 18 02 14
- And that's master: Screenshot 2021-12-16 at 18 02 21

I know this project is not under development, but personally, if we have a choice, I'd rather leave it with some older version of UI library (or whatever else broke it), rather than leave it half-broken. As then it'd be difficult for someone to pick it up if necessary (and since we just used it for DESE, who knows about the future :wink:). Also, there's a small chance that some LARA activities link to this model using the `master` branch (even if they should not).

TravisCI almost works - S3 deploy fails silently:

`$ deploy/s3_deploy.sh
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v2.12.3/s3_website.jar into /home/travis/.rvm/gems/ruby-2.5.3/gems/s3_website-2.12.3/s3_website-2.12.3.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jruby.Ruby.newInstance(Ruby.java:266)
	at s3.website.Ruby$.rubyRuntime$lzycompute(Ruby.scala:4)
	at s3.website.Ruby$.rubyRuntime(Ruby.scala:4)
	at s3.website.model.Config$$anonfun$12.apply(Config.scala:196)
	at s3.website.model.Config$$anonfun$12.apply(Config.scala:194)
	at scala.util.Try$.apply(Try.scala:192)
	at s3.website.model.Config$.erbEval(Config.scala:194)
	at s3.website.model.Site$$anonfun$2.apply(Site.scala:28)
	at s3.website.model.Site$$anonfun$2.apply(Site.scala:27)
	at scala.util.Success.flatMap(Try.scala:231)
	at s3.website.model.Site$.parseConfig(Site.scala:27)
	at s3.website.model.Site$.loadSite(Site.scala:90)
	at s3.website.Push$.push(Push.scala:62)
	at s3.website.Push$.main(Push.scala:40)
	at s3.website.Push.main(Push.scala)
Caused by: java.lang.RuntimeException: unsupported Java version: 11
	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1878)
	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1585)
	... 15 more
`

This error sounds familiar. I bet we used to lock Ubuntu version to one of the older ones to prevent that?

**Comment by kswenson** [comment]
I hadn't noticed the layout change but now that you point it out it's obvious. 🤦 And yes, locking node.js version on Travis seems like a likely fix there. I'll take a quick look at both issues.

**Comment by kswenson** [comment]
I believe I have fixed the layout issues. I can't explain why the previous code ever worked, so I have no explanation for how my changes broke them.

The layout of the controls was being mediated by the `pull-right` class. The `pull-right` class was renamed in Bootstrap 4 (`main` was on 4.1.3; I only updated it to 4.6.1) to `float-right`. A search through the bootstrap sources in version 4.1.3 found no reference to `pull-right`. It's not that it was deprecated; it's completely gone. Yet the .css for it is clearly in the running app at `/branch/master`, I just can't explain how it got there. 🤷 The fix is simply to use the new name: `float-right`.

Similarly, the layout of the CC logo in the footer is controlled by a block of CSS in `main.css`. According to the `webpack.config.js` on master, this is how `.css` files were being processed before any of my changes:
```javascript
      {
        test: /\.css$/,
        use: [{
          loader: 'css-loader'
        }]
      },
```
which according to my (admittedly incomplete) understanding of things means that the CSS was being processed but the results weren't being put anywhere. The fix was simply to add the `style-loader` so that the results get injected into the page, but again I don't understand how it worked previously. 🤷

**Comment by kswenson** [comment]
Fixed the Travis deploy; testable at https://models-resources.concord.org/grasp-seasons/branch/180348539-update-project/index.html.

**Comment by pjanik** [comment]
Now it looks pretty much like the master branch. I can see some very minor issues in buttons, but it's perfectly usable and probably not worth spending more time on that given state of this project. Thank you!

**Comment by kswenson** [comment]
> Now it looks pretty much like the master branch. I can see some very minor issues in buttons, but it's perfectly usable and probably not worth spending more time on that given state of this project. Thank you!

Do you think it should be merged or left as an outstanding PR? If the former, should this comment be considered an approval? (The PR is still in its "changes requested" state from earlier.)

**Comment by pjanik** [comment]
Ah, I forgot to update review status. Sure, I'd merge it.

**Pull request merged**
